services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
      - /data:/octoprint
    environment:
      - MJPG_STREAMER_INPUT=-n -r 1920x1080 -br 0 -co 32 -sa 64 -sh 10
      - ENABLE_MJPG_STREAMER=true
