services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      TZ: 'Europe/Berlin'
      DNSSEC: true
      PIHOLE_UID: 0
    cap_add:
      - NET_ADMIN
    volumes:
      - /data/etc-pihole:/etc/pihole
      - /data/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
