esphome:
    basic-auth:
        auth: ENC[AES256_GCM,data:3Y4Mg82BjpPecdr8DmVy8SQkN26YL6CtpKCQiknrMDJ7FjUendZ4P8SS+R8rVhMEovIpi0o=,iv:iKtM087n/80EVf2FWJcHwuiegn8qyQIlyvzuhyZ/EkM=,tag:I92z5iI23q7e1B5m0GlduA==,type:str]
        token: ENC[AES256_GCM,data:W4em+xF4lHuCg7QfDFsW1tUBt6TKDoH8bzlMDeWq1HaFlJCccWA2U+pC+3LXko3BgstxuFdJQ+WDhwqw/P64jdKtedyBhMA/1yzN2TBFz1BJjAcvJln60u6fLOqmMoQTaQGUUiwUq9UgLsw+5y0z3UqeYbc9c//CcJGopqs7Y+FKXkyBM76LzrVGyj43Xy0YNLsh0WmbTQuhn8G1HmTKfLHZmRQgrCLxZR0ttto/8Hk2MLC/e9WdXUbBov7seQGsUo7TF54DhphX1mrt3n5JZWl/xwZk9jPl/xfg/ea0ig5lSJt8/rat8RBJt9buN4acUAqVW20rsVcNNA==,iv:1QvelsUJy9jqxYPYfM4OkSKrOXroIyLuZoVYqSTb9iQ=,tag:QWJTfpP4Hpwtwhzt9ZDYfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTDBLZys3Yzk4WkQwQ1Ni
            WU81cWFuMDJSN2s0Vm50cDY0UERxR3V2VVFrClFZMno0SDNvK09vN0QzMjhUUzJL
            SzFhYWx0NHdGKzJUb3p3djZxNTFud1UKLS0tIDdrNWQ4QlVhaWx5bHJhOEdPWVVw
            WEFodDhIdmtJTURncTNTeUdveDNmTVEKc2eoIDshbWsGP6k4/qQD/Hc6Ib9Or6nj
            ahy6qWgofwK5HAFqFWGKsuSz7PZ2muS5j8n5NWjXYXdsZdewdp3Zwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t8gkcjjs2jsu5umdmpdkflgdajugk6dcc52fr6wecem7f954ruuq4nn3sw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZFVDWkd3NHozd0VyMmth
            aXVPeU9DRUZqdE0vYnZ6ditiVVI0aitGWFFrCklZbnVQb05NL01aalV6OWZHYmd4
            QmNJeTFUOWY4WmQ0cXhjN2JkUXlodncKLS0tIHdxcGw1bkhMalZ4encydHlqZC9i
            U0FzNmRGMGNWR3RaamFUYWpXSlRIVm8KPgV5P4QVbIEvQNcenl6H9HzhezfeejN9
            y7ak2XhgZwiLqPNTDU/GucLm53MHJQpidZFxdsZ50tgOFaAayROs4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T14:05:24Z"
    mac: ENC[AES256_GCM,data:b9MUQ0rWg36HOtwcFMW2zmMq658sawTa55hiD4SfikjAsaNRsbGs1tfgZuKHRJoJkHH+R/pfuBroLbjU4xbu8gTzQYXBjIvb7LktLIpM8qAYnX6Vyjrrz8XJPe6scJeiVMn4hgczEl15c6Ah1UZQkrBs3uAf7F9PvTzGI2jSfI8=,iv:CinSJREJu3fLcsYn8rRhCNysrsq2S78IAaeiojLY0hI=,tag:NQRLZ9nWbsDH26Upcvp/KA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
