esphome:
    basic-auth:
        auth: ENC[AES256_GCM,data:usj30NI6aKRwZpQSKFkhCqwGmWx82DTIm2O9jYOZYst6qrSAIAeJCZQWNKY7D3jYAi6dggw=,iv:E1peSCTz2yzzRKHl4845Vro1mTHSBEjT5LsgiLa4ano=,tag:NVJFdIQfWlaonufytKEKMQ==,type:str]
        token: ENC[AES256_GCM,data:UoIhSEko9AC8RRVXFwfQ6NZ2cOWVPdMiMcqJA7XscImnEKeAvHr3IhG/l+9L0MkolAecAUbI4lSvfnEcttDWgwgxESQaE96OH16u2B9cQy4B2w0CSs+x9Y/2e9vdjZltuQ35pXmzXjczp11yeY+J4Rpt9hpqOH1hAlCkGI5ANkn9EjkV74DlXIYMxoK72HYKN3u914Pb21vEzWAahyGxBwk0wWYaxIkNPpiNjJBu98bWeRbGbTCaQEO71E7xMeZHOdeX9c7CLLfHcp3IjO3ILwO84eXCR3cnhI7ZTEERcBrojygGdk04cJTbpRZur0fxrFY76xjn/6B3g+yWv8RgeoTahQE+36haF4Filhs=,iv:nUXMkvybtbJS1yLYN6kRbiesB381NqEzLdH1z/eq39s=,tag:NBPuvMEGeMCI2NyFYdPFKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcW81NGI0Y1dzSjg5dTY0
            M3N3aWNybXYyYm5JM2l1a0lwRHp2aWFiOWtvCktvbzlWZU9Vb1NaK2oyQWd1L2dZ
            eFhpSHZBaEc4WUJVNzJON2xBSVVEbHcKLS0tIGxVS2diMDVQazRFU25Vb1RFR2h3
            Q001M2FyVEdmditLeXUzY2h5a0FaSkkK3dJiptmyv4uo4F+jUSiA2qWQ3PGwF8OU
            4WNG6ar9cT/MDS3zV6+tFlJGW7ANbIKB2qtxY/cXXMqyXfF7tEqhmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T01:57:00Z"
    mac: ENC[AES256_GCM,data:NxFWPiG5z6sraN+S7kIZ8qSFKcN8wnxUKQcnFGWzpKICPvtjO1qCGfh43Jrm9eEZcfDB+6jwf0OSOYhxN5atYkpt8o2ny34tgRFse44vJt+Bf1OoaYEIR14nXLvsXfK/o3cl80vshxV3iKgOuvXZYtDolkmgiOdfNV58uIaVmYc=,iv:6yZ8nfbVmq5zW23nx6rxqD1LEs8KYogrNBT3CZJnf1o=,tag:pvNQztvtQ6B1ctsVXFsE4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
