esphome:
    basic-auth:
        auth: ENC[AES256_GCM,data:ayToeKeIW2VrrjKeEOYz7+6bC4gfSv/nqMCaNF6yUGHh8/8jmTxYKcS5iqALBhasB6YguPM=,iv:GcAOkfUADarMoWZyo1fiXy+R1QiMNDmH2dU06lErwbg=,tag:AdVhLLYnou1TvroWMR3TIQ==,type:str]
        token: ENC[AES256_GCM,data:Dhd09kroyr9+E9Thl1jrCZ89EraBNCURl8wBhNhcomY0FlQ9DRs7Mmt5w5FBYuEtC8Qr6q92wqfqDNeRu73o7EDJ4vCtmQlm,iv:A0eqgygv+UgNn/QHbb+0BaR/cQDocQ977844TypuTcM=,tag:v3Mjbab2c6It3b56LoGgpQ==,type:str]
sops:
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY2M0ckkyaE4rMUI0ci9B
            S0JqVGsySWI2eXJjZW11Nm1nd2pVOFQ3T1NrCnFrelFpa0lUNVN2ekUzZUpPUzJC
            MDlsS3VoN0RVMkpEVWpMb0FSTE9raVEKLS0tIDhMeEJ1aTJDNDJHeWNLRW5ITFpM
            K0JFMm9xL1kwUWEwOSsyc3hBLzlhTGcK6/3V59px3Y1Mw6jqmTvHlSfZolTC4j0Z
            Sm5rmeC6utfvNh1EJXmE9UOAx5MMHc9ZPAQbL3VUE1+GdQMgNziRzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rjrlkz52zk6ne6cpf934qcduwnt0eg30gd0eqvywfg5m6shha54sdp3p70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VENmNTBMNXBMN3JQakQw
            WEM1L1A3RHNaUGVRMVNpWEw3Vm1GYjNnVG5RCmU3M1B2eVc1ZktxSVVDWkJiVldt
            Y0FrUWYzdGpJYkhaWVpDYmZMREVvSE0KLS0tIHgwSFhieWU3RzM2YzJtMkxjSktr
            N2dmREY3VysxUEcrdWxwZUczUGh4SjAKX+LAsWMXiv609IuHmauXYUam0HeDn80V
            lmIZuKFG6OKMqfucptMwh15UihT93EaomM0sEKL1G8RhFTiPvY01Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T23:14:29Z"
    mac: ENC[AES256_GCM,data:ShtYQbsgvvicHVN0ZBzQBM4FBO+l2rsZst0XJas7k/oJt+5zcQminTmHTa+hE4k6cfPMyKfZ12QaIkvZ83ueiNBipcfUwC4jU7/1bR/2gBvW4L1e+vHKDiaf9n9CLda4e46v10xXncsZkqO3iaT6ontYa2pmL2BRGopGYTiTEWU=,iv:ceVyI3x9PdAfLwye4kHqS9mvWTodY98TtgFl4/meoO4=,tag:cbcTSJ6+jW49H/PLx/QBlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
