services:
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    env_file:
      # DB requires MYSQL_{ ROOT_PASSWORD, PASSWORD }
      # but MYSQL_ROOT_PASSWORD should be kept secret to this service
      - /data/.env-database
      - /data/.env-database-root
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $${REDIS_HOST_PASSWORD}"
    environment:
      TZ: Europe/Berlin
    env_file:
      # Redis requires REDIS_HOST_PASSWORD
      - /data/.env-redis
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

  app:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
      - redis
    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      TZ: Europe/Berlin
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.davidkopczynski.com localhost
      TRUSTED_PROXIES: 10.0.1.0
      OVERWRITEHOST: cloud.davidkopczynski.com
      OVERWRITEPROTOCOL: https
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
    env_file:
      # Passwords are also required for Nextcloud
      - /data/.env-database
      - /data/.env-redis
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5
