services:
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
    env_file:
      # DB requires MYSQL_{ ROOT_PASSWORD, PASSWORD, DATABASE, USER }
      - /data/.env-database
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $${REDIS_HOST_PASSWORD}"
    environment:
      TZ: Europe/Berlin
    env_file:
      # Redis requires REDIS_{ HOST_PASSWORD }
      - /data/.env-redis
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

  app:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
      - redis
    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      TZ: Europe/Berlin
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.davidkopczynski.com localhost
      TRUSTED_PROXIES: 10.0.1.0
      OVERWRITEHOST: cloud.davidkopczynski.com
      OVERWRITEPROTOCOL: https
    env_file:
      # Nextcloud requires environments from DB and Redis on top of:
      # MYSQL_HOST and REDIS_HOST with the name of the containers
      - /data/.env-database
      - /data/.env-redis
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5
