x-database: &x-database
  MYSQL_ROOT_PASSWORD: ***REMOVED***
  MYSQL_PASSWORD:      ***REMOVED***
  MYSQL_DATABASE:      nextcloud
  MYSQL_USER:          nextcloud
  MYSQL_HOST:          db

x-redis: &x-redis
  REDIS_HOST_PASSWORD: ***REMOVED***
  REDIS_HOST:          redis

services:
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      <<: *x-database
      TZ: Europe/Berlin

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $${REDIS_HOST_PASSWORD}"
    environment:
      <<: *x-redis
      TZ: Europe/Berlin

  app:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    ports:
      - 11000:80
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      <<: [*x-database, *x-redis]
      TZ: Europe/Berlin
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.davidkopczynski.com localhost
      TRUSTED_PROXIES: 10.0.1.0
      OVERWRITEHOST: cloud.davidkopczynski.com
      OVERWRITEPROTOCOL: https
