services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - default
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./sites/:/etc/nginx/sites-enabled/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    networks:
      - default
    environment:
      - TZ=Europe/Berlin
      - TUNNEL_TOKEN=***REMOVED***
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  default:
    name: nginx
