services:
  nginx: &nginx
    image: nginx:latest
    container_name: nginx
    networks:
      - default
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites:/etc/nginx/sites-enabled:ro
      - ./stream:/etc/nginx/stream:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped

  test:
    <<: *nginx
    container_name: nginx-test
    command: nginx -t
    restart: no

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    networks:
      - default
    environment:
      - TZ=Europe/Berlin
      # For more see: https://one.dash.cloudflare.com/810c6c47e0dd11a27a3a6ef2da2589f8/networks/tunnels/cfd_tunnel/535af01d-1f8b-4576-9a5e-fd56aed132aa/edit?tab=publicHostname
      - TUNNEL_TOKEN=***REMOVED***
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  default:
    name: nginx
