services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./config:/etc/nginx/config
      - ./sites:/etc/nginx/sites-enabled
      - ./ssl:/etc/nginx/ssl
      - ./streams:/etc/nginx/streams-enabled
        # For the origin certificates, SST/TLS encrytion must be set to Full(strict)
        # and the certificates placed here as "davidkopczynski.com.pem" and "davidkopczynski.com.key".
        # Ideally, the origin pulls are also authenticated in the settings.
      - /data/cloudflare:/etc/nginx/ssl-cloudflare:ro
      - ssl:/etc/nginx/ssl-basic:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

  certbot:
    image: certbot/dns-cloudflare:latest
    command: >
      # Run this container once a day and restart Nginx if required
      certonly
        --non-interactive
        --verbose
        --keep-until-expiring
        --dns-cloudflare
        --dns-cloudflare-credentials /root/cloudflare.ini
        --agree-tos
        --no-eff-email
        --email mail@davidkopczynski.com
        -d           davidkopczynski.com
        -d         *.davidkopczynski.com
    container_name: certbot
    environment:
      - TZ=Europe/Berlin
    volumes:
        # This cloudflare.ini with "dns_cloudflare_api_token" is taken from user api tokens
        # with Zone.DNS permissions.
      - /data/.env-cloudflare:/root/cloudflare.ini:ro
      - ssl:/etc/letsencrypt
    profiles: ["certbot"]
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
        # This also requires a cloudflare user api token
        # with Zone.DNS permissions.
      - /data/ddns-config.json:/config.json:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5

volumes:
  ssl:
