services:
  nginx: &nginx
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        COPY ./nginx.conf /etc/nginx/nginx.conf
        COPY ./config /etc/nginx/conf.d/config
        COPY ./sites /etc/nginx/sites-enabled
        COPY ./streams /etc/nginx/streams-enabled
    container_name: nginx
    networks:
      - default
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped

  test:
    <<: *nginx
    container_name: nginx-test
    command: nginx -t
    restart: no

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    networks:
      - default
    environment:
      - TZ=Europe/Berlin
      - TUNNEL_TOKEN=***REMOVED***
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  default:
    name: nginx
