services:
  nginx:
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        COPY ./nginx.conf /etc/nginx/nginx.conf
        COPY ./config /etc/nginx/conf.d
        COPY ./sites /etc/nginx/sites-enabled
        COPY ./streams /etc/nginx/streams-enabled
    container_name: nginx
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      - TZ=Europe/Berlin
    env_file:
      - /data/.env-cloudflared
    depends_on:
      - nginx
    restart: unless-stopped
